# -*- coding: utf-8 -*-
"""why do startup fails

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u_7SZfM-Q3w3ihH6ksfHjru439O7Qu3I

## Load Data from Google Drive

To access files stored in your Google Drive, you need to mount your Drive to this Colab runtime. This will prompt you to authenticate your Google account.
"""

from google.colab import drive
drive.mount('/content/drive')

import os

base_path = "/content/drive/MyDrive/startup analysis"

for folder in ["archive (1)", "archive (2)"]:
    full_path = f"{base_path}/{folder}"
    print(f"\n{folder}:")
    for root, dirs, files in os.walk(full_path):
        for f in files:
            print(" ", os.path.join(root, f).replace(full_path, ""))

import duckdb

con = duckdb.connect(f"{base_path}/startup_analysis.duckdb")

ideaproof_path = f'{base_path}/ideaproof-startup-failures (1).csv'

con.execute(f"""
CREATE TABLE ideaproof AS
SELECT * FROM read_csv_auto('{ideaproof_path}', ignore_errors=true)
""")

print(con.execute("SELECT COUNT(*) FROM ideaproof").fetchone())
con.execute("SELECT * FROM ideaproof LIMIT 5").df()

import os
import duckdb

base_path = "/content/drive/MyDrive/startup analysis"
con = duckdb.connect(f"{base_path}/startup_analysis.duckdb")

# Map expected filenames to clean table names
file_to_table = {
    "objects.csv": "cb_objects",
    "funding_rounds.csv": "cb_funding_rounds",
    "acquisitions.csv": "cb_acquisitions",
    "ipos.csv": "cb_ipos",
    "people.csv": "cb_people",
    "relationships.csv": "cb_relationships",
    "degrees.csv": "cb_degrees",
    "milestones.csv": "cb_milestones",
    "offices.csv": "cb_offices",
    "investments.csv": "cb_investments",
    "funds.csv": "cb_funds",
    "ks-projects-201801.csv": "kickstarter",
    "startup failures.csv": "fail_master",
}

loaded = {}
skipped = []

for root, dirs, files in os.walk(base_path):
    for f in files:
        if not f.lower().endswith(".csv"):
            continue
        key = f.lower()
        table_name = file_to_table.get(key)
        if table_name and table_name not in loaded:
            full_path = os.path.join(root, f)
            try:
                con.execute(f"""
                    CREATE OR REPLACE TABLE {table_name} AS
                    SELECT * FROM read_csv_auto('{full_path}', ignore_errors=true)
                """)
                count = con.execute(f"SELECT COUNT(*) FROM {table_name}").fetchone()[0]
                loaded[table_name] = (full_path, count)
                print(f"Loaded {table_name}: {count} rows  <- {full_path}")
            except Exception as e:
                skipped.append((full_path, str(e)))

print("\n--- Not loaded (mapped but failed) ---")
for path, err in skipped:
    print(path, "->", err)

print("\n--- Tables expected but never found ---")
for fname, tbl in file_to_table.items():
    if tbl not in loaded:
        print(f"Missing: {fname} -> {tbl}")

import os

print("=== Everything under Drive 'startup analysis' ===")
for root, dirs, files in os.walk(base_path):
    for f in files:
        print(os.path.join(root, f))

print("\n=== Kagglehub local cache (if session still alive) ===")
cache_root = "/root/.cache/kagglehub/datasets"
if os.path.exists(cache_root):
    for root, dirs, files in os.walk(cache_root):
        for f in files:
            print(os.path.join(root, f))
else:
    print("Cache not found — likely a fresh session, kagglehub files are gone.")

import shutil, os

base_path = "/content/drive/MyDrive/startup analysis"

shutil.copytree(
    "/root/.cache/kagglehub/datasets/justinas/startup-investments/versions/1",
    f"{base_path}/crunchbase", dirs_exist_ok=True
)

shutil.copytree(
    "/root/.cache/kagglehub/datasets/kemical/kickstarter-projects/versions/7",
    f"{base_path}/kickstarter", dirs_exist_ok=True
)

print("Done. Contents now in Drive:")
for root, dirs, files in os.walk(base_path):
    for f in files:
        print(os.path.join(root, f))

import duckdb, os

base_path = "/content/drive/MyDrive/startup analysis"
con = duckdb.connect(f"{base_path}/startup_analysis.duckdb")

file_to_table = {
    "objects.csv": "cb_objects",
    "funding_rounds.csv": "cb_funding_rounds",
    "acquisitions.csv": "cb_acquisitions",
    "ipos.csv": "cb_ipos",
    "people.csv": "cb_people",
    "relationships.csv": "cb_relationships",
    "degrees.csv": "cb_degrees",
    "milestones.csv": "cb_milestones",
    "offices.csv": "cb_offices",
    "investments.csv": "cb_investments",
    "funds.csv": "cb_funds",
    "ks-projects-201801.csv": "kickstarter",
    "startup failures.csv": "fail_master",
    "ideaproof-startup-failures (1).csv": "ideaproof",
}

loaded = {}
for root, dirs, files in os.walk(base_path):
    for f in files:
        key = f.lower()
        table_name = file_to_table.get(key)
        if table_name and table_name not in loaded:
            full_path = os.path.join(root, f)
            con.execute(f"""
                CREATE OR REPLACE TABLE {table_name} AS
                SELECT * FROM read_csv_auto('{full_path}', ignore_errors=true)
            """)
            count = con.execute(f"SELECT COUNT(*) FROM {table_name}").fetchone()[0]
            loaded[table_name] = count
            print(f"Loaded {table_name}: {count} rows")

missing = [t for t in file_to_table.values() if t not in loaded]
print("\nStill missing:", missing if missing else "none — everything loaded")

import os

# --- 1. Sector file subset check ---
sector_files = {
    "Startup Failure (Health Care).csv": "fail_healthcare",
    "Startup Failure (Manufactures).csv": "fail_manufacturing",
    "Startup Failure (Retail Trade).csv": "fail_retail",
    "Startup Failure (Finance and Insurance).csv": "fail_finance",
    "Startup Failures (Information Sector).csv": "fail_info",
    "Startup Failure (Food and services).csv": "fail_food",
}
for fname, tbl in sector_files.items():
    for root, dirs, files in os.walk(base_path):
        if fname in files:
            con.execute(f"CREATE OR REPLACE TABLE {tbl} AS SELECT * FROM read_csv_auto('{os.path.join(root, fname)}', ignore_errors=true)")
total_sector = sum(con.execute(f"SELECT COUNT(*) FROM {t}").fetchone()[0] for t in sector_files.values())

# --- 2. Column structures ---
ideaproof_cols = con.execute("DESCRIBE ideaproof").df()['column_name'].tolist()
fail_master_cols = con.execute("DESCRIBE fail_master").df()['column_name'].tolist()
cb_objects_cols = con.execute("DESCRIBE cb_objects").df()['column_name'].tolist()

name_col_fail = 'name' if 'name' in fail_master_cols else [c for c in fail_master_cols if 'name' in c.lower()][0]
name_col_cb = 'name' if 'name' in cb_objects_cols else [c for c in cb_objects_cols if 'name' in c.lower()][0]

# --- 3. Overlap checks ---
overlap_idea_fail = con.execute(f"""
    SELECT COUNT(*) FROM ideaproof i JOIN fail_master f
    ON trim(regexp_replace(lower(i.name), '[^a-z0-9 ]', '', 'g')) = trim(regexp_replace(lower(f.{name_col_fail}), '[^a-z0-9 ]', '', 'g'))
""").fetchone()[0]

overlap_idea_cb = con.execute(f"""
    SELECT COUNT(*) FROM ideaproof i JOIN cb_objects c
    ON trim(regexp_replace(lower(i.name), '[^a-z0-9 ]', '', 'g')) = trim(regexp_replace(lower(c.{name_col_cb}), '[^a-z0-9 ]', '', 'g'))
""").fetchone()[0]

# --- FINAL REPORT ---
print("="*50)
print("SECTOR FILES: sum =", total_sector, "| fail_master =", 815, "->", "SUBSET, ignore sector files" if total_sector <= 900 else "NOT a clean subset, needs review")
print("="*50)
print("ideaproof columns:", ideaproof_cols)
print("fail_master columns:", fail_master_cols)
print("cb_objects columns:", cb_objects_cols[:10], "...")
print("="*50)
print(f"ideaproof <-> fail_master overlap: {overlap_idea_fail} / 1028")
print(f"ideaproof <-> cb_objects overlap:  {overlap_idea_cb} / 1028")
print("="*50)

# Filter to companies only (cb_objects also contains people, funds, etc.)
con.execute("""
CREATE OR REPLACE TABLE cb_companies AS
SELECT * FROM cb_objects WHERE entity_type = 'Company'
""")
print("Crunchbase companies only:", con.execute("SELECT COUNT(*) FROM cb_companies").fetchone()[0])

# Try matching against Crunchbase's own normalized_name field first
match_v2 = con.execute("""
SELECT COUNT(*) FROM ideaproof i
JOIN cb_companies c
  ON trim(regexp_replace(lower(i.name), '[^a-z0-9 ]', '', 'g')) = lower(c.normalized_name)
""").fetchone()[0]
print("Match using cb's normalized_name:", match_v2, "/ 1028")

# Build crosswalk from best exact match
con.execute("""
CREATE OR REPLACE TABLE company_crosswalk AS
SELECT i.slug AS ideaproof_slug, c.id AS crunchbase_id, 'exact' AS match_type
FROM ideaproof i
JOIN cb_companies c
  ON trim(regexp_replace(lower(i.name), '[^a-z0-9 ]', '', 'g')) = lower(c.normalized_name)
""")
print("Crosswalk rows so far:", con.execute("SELECT COUNT(*) FROM company_crosswalk").fetchone()[0])

con.execute("""
CREATE OR REPLACE TABLE enriched AS
SELECT
    i.slug,
    i.name,
    i.founded,
    i.failed,
    (i.failed - i.founded) AS lifespan_years,
    i.country,
    i.industry,
    i.funding_raised_usd_millions AS ideaproof_funding_musd,
    i.failure_reason,
    i.lesson,
    cw.crunchbase_id,
    c.founded_at AS cb_founded_at,
    c.status AS cb_status,
    fr.total_funding_usd,
    fr.num_funding_rounds,
    fr.first_round_date,
    fr.last_round_date
FROM ideaproof i
JOIN company_crosswalk cw ON i.slug = cw.ideaproof_slug
JOIN cb_companies c ON cw.crunchbase_id = c.id
LEFT JOIN (
    SELECT object_id,
           SUM(raised_amount_usd) AS total_funding_usd,
           COUNT(*) AS num_funding_rounds,
           MIN(funded_at) AS first_round_date,
           MAX(funded_at) AS last_round_date
    FROM cb_funding_rounds
    GROUP BY object_id
) fr ON c.id = fr.object_id
""")

print("Enriched rows:", con.execute("SELECT COUNT(*) FROM enriched").fetchone()[0])
con.execute("SELECT * FROM enriched LIMIT 5").df()

con.execute("""
CREATE OR REPLACE TABLE enriched_full AS
SELECT e.*,
       COALESCE(team.team_size, 0) AS founding_team_size,
       COALESCE(inv.investor_count, 0) AS distinct_investors
FROM enriched e
LEFT JOIN (
    SELECT relationship_object_id AS object_id, COUNT(DISTINCT person_object_id) AS team_size
    FROM cb_relationships
    GROUP BY relationship_object_id
) team ON e.crunchbase_id = team.object_id
LEFT JOIN (
    SELECT funded_object_id AS object_id, COUNT(DISTINCT investor_object_id) AS investor_count
    FROM cb_investments
    GROUP BY funded_object_id
) inv ON e.crunchbase_id = inv.object_id
""")

con.execute("SELECT * FROM enriched_full LIMIT 5").df()

con.execute("""
SELECT failure_reason,
       COUNT(*) AS n,
       ROUND(AVG(total_funding_usd)/1e6, 1) AS avg_funding_musd,
       ROUND(AVG(lifespan_years), 1) AS avg_lifespan_years,
       ROUND(AVG(founding_team_size), 1) AS avg_team_size
FROM enriched_full
GROUP BY failure_reason
ORDER BY n DESC
LIMIT 15
""").df()

taxonomy_rules = [
    ("Ran out of cash / funding",     ["cash", "burn", "runway", "could not raise", "failed to raise", "ran out"]),
    ("Poor unit economics",           ["unit economics", "unprofitable", "margin", "profitability"]),
    ("No market need",                ["no market need", "solution in search of", "lack of product-market fit", "product-market fit"]),
    ("Got outcompeted",               ["competitive", "competitor", "outcompeted", "asphyxiation", "consolidated market", "winner-take-all"]),
    ("Regulatory / legal issues",     ["regulatory", "regulation", "banned", "legal", "compliance", "license"]),
    ("Team / governance issues",      ["founder", "governance", "fraud", "mismanagement", "leadership"]),
    ("Pivot failure",                 ["pivot"]),
    ("Macro / external shock",        ["covid", "recession", "downturn", "macro", "market crash", "interest rate"]),
    ("Acquisition / shutdown by parent", ["acquired then shut", "parent company", "shut down by"]),
]

